/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.*;
import classes.*;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Maria Heloisa Souza
 */
public class Etapa3_2 extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    private String nome; 
    private int cod_u; 

    public int getCod_u() {
        return cod_u;
    }

    public void setCod_u(int cod_u) {
        this.cod_u = cod_u;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }
    public Etapa3_2() {
        initComponents();
        Color vinho = new Color(66,0,0);
        this.getContentPane().setBackground(vinho);
        this.setLocationRelativeTo(null);
        
         BdCursos bd = new BdCursos();
         ArrayList vetCursos = bd.buscaCursosGeral();    
            Curso c; 
            c = (Curso) vetCursos.get(1);
     
             jLText.setText("Informações sobre "+c.getNome_curso());
             taAreaA.setLineWrap(true);
             taPontosP.setLineWrap(true);
             taPontosN.setLineWrap(true);
             taAreaA.append(c.getArea_atuacao()+"\n");
             taPontosP.append(c.getPontos_positivos());
             taPontosN.append(c.getPontos_negativos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAvancar = new javax.swing.JButton();
        jLText = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jlEnsino = new javax.swing.JLabel();
        jlSobreCurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAreaA = new javax.swing.JTextArea();
        jbPositivo1 = new javax.swing.JButton();
        JbNegativo1 = new javax.swing.JButton();
        jlSisu = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taPontosN = new javax.swing.JTextArea();
        JbNegativo2 = new javax.swing.JButton();
        jbPositivo2 = new javax.swing.JButton();
        jlSobreCurso1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taPontosP = new javax.swing.JTextArea();
        JbNegativo3 = new javax.swing.JButton();
        jbPositivo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Etapa3_2");
        setBackground(new java.awt.Color(66, 0, 0));

        jbAvancar.setBackground(new java.awt.Color(153, 102, 51));
        jbAvancar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbAvancar.setForeground(new java.awt.Color(255, 255, 255));
        jbAvancar.setText("Avançar");
        jbAvancar.setToolTipText("");
        jbAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAvancarActionPerformed(evt);
            }
        });

        jLText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLText.setForeground(new java.awt.Color(255, 255, 255));
        jLText.setText("Informações sobre [NOME DO CURSO]");

        jbVoltar.setBackground(new java.awt.Color(153, 102, 51));
        jbVoltar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jbVoltar.setText("Voltar");
        jbVoltar.setToolTipText("");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlEnsino.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlEnsino.setForeground(new java.awt.Color(66, 0, 0));
        jlEnsino.setText("* Carreira");

        jlSobreCurso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSobreCurso.setForeground(new java.awt.Color(66, 0, 0));
        jlSobreCurso.setText("º Área de atuação ou especialização");

        taAreaA.setEditable(false);
        taAreaA.setColumns(20);
        taAreaA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        taAreaA.setForeground(new java.awt.Color(66, 0, 0));
        taAreaA.setRows(5);
        taAreaA.setFocusable(false);
        jScrollPane1.setViewportView(taAreaA);

        jbPositivo1.setBackground(new java.awt.Color(0, 153, 0));
        jbPositivo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbPositivo1.setForeground(new java.awt.Color(255, 255, 255));
        jbPositivo1.setText("Positivo");
        jbPositivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPositivo1ActionPerformed(evt);
            }
        });

        JbNegativo1.setBackground(new java.awt.Color(153, 0, 0));
        JbNegativo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JbNegativo1.setForeground(new java.awt.Color(255, 255, 255));
        JbNegativo1.setText("Negativo");
        JbNegativo1.setToolTipText("");
        JbNegativo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbNegativo1ActionPerformed(evt);
            }
        });

        jlSisu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSisu.setForeground(new java.awt.Color(66, 0, 0));
        jlSisu.setText("º Pontos positivos");

        taPontosN.setEditable(false);
        taPontosN.setColumns(20);
        taPontosN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        taPontosN.setForeground(new java.awt.Color(66, 0, 0));
        taPontosN.setRows(5);
        taPontosN.setFocusable(false);
        jScrollPane3.setViewportView(taPontosN);

        JbNegativo2.setBackground(new java.awt.Color(153, 0, 0));
        JbNegativo2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JbNegativo2.setForeground(new java.awt.Color(255, 255, 255));
        JbNegativo2.setText("Negativo");
        JbNegativo2.setToolTipText("");
        JbNegativo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbNegativo2ActionPerformed(evt);
            }
        });

        jbPositivo2.setBackground(new java.awt.Color(0, 153, 0));
        jbPositivo2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbPositivo2.setForeground(new java.awt.Color(255, 255, 255));
        jbPositivo2.setText("Positivo");
        jbPositivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPositivo2ActionPerformed(evt);
            }
        });

        jlSobreCurso1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSobreCurso1.setForeground(new java.awt.Color(66, 0, 0));
        jlSobreCurso1.setText("º Pontos negativos");

        taPontosP.setEditable(false);
        taPontosP.setColumns(20);
        taPontosP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        taPontosP.setForeground(new java.awt.Color(66, 0, 0));
        taPontosP.setRows(5);
        taPontosP.setFocusable(false);
        jScrollPane4.setViewportView(taPontosP);

        JbNegativo3.setBackground(new java.awt.Color(153, 0, 0));
        JbNegativo3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JbNegativo3.setForeground(new java.awt.Color(255, 255, 255));
        JbNegativo3.setText("Negativo");
        JbNegativo3.setToolTipText("");
        JbNegativo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbNegativo3ActionPerformed(evt);
            }
        });

        jbPositivo3.setBackground(new java.awt.Color(0, 153, 0));
        jbPositivo3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbPositivo3.setForeground(new java.awt.Color(255, 255, 255));
        jbPositivo3.setText("Positivo");
        jbPositivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPositivo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(JbNegativo2)
                        .addGap(18, 18, 18)
                        .addComponent(jbPositivo2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(JbNegativo3)
                        .addGap(18, 18, 18)
                        .addComponent(jbPositivo3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                            .addComponent(jlSisu)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlSobreCurso1))
                            .addComponent(jlSobreCurso))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 256, Short.MAX_VALUE)
                .addComponent(JbNegativo1)
                .addGap(18, 18, 18)
                .addComponent(jbPositivo1)
                .addGap(269, 269, 269))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jlSobreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPositivo1)
                    .addComponent(JbNegativo1))
                .addGap(20, 20, 20)
                .addComponent(jlSisu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbNegativo2)
                    .addComponent(jbPositivo2))
                .addGap(20, 20, 20)
                .addComponent(jlSobreCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbNegativo3)
                    .addComponent(jbPositivo3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAvancar)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLText)
                        .addContainerGap(344, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAvancar)
                    .addComponent(jbVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
           Etapa3_1 p = new Etapa3_1();
            p.setVisible(true);
            p.setCod_u(cod_u);
            p.setLocationRelativeTo(null);
            dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void JbNegativo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbNegativo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbNegativo1ActionPerformed

    private void jbPositivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPositivo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPositivo1ActionPerformed

    private void JbNegativo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbNegativo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbNegativo2ActionPerformed

    private void jbPositivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPositivo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPositivo2ActionPerformed

    private void JbNegativo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbNegativo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbNegativo3ActionPerformed

    private void jbPositivo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPositivo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPositivo3ActionPerformed

    private void jbAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAvancarActionPerformed
            Etapa3_3 p = new Etapa3_3();
            p.setCod_u(cod_u);
            p.setNome(nome);
            p.setVisible(true);
            p.setLocationRelativeTo(null);
            dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jbAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etapa3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etapa3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etapa3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etapa3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etapa3_2().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbNegativo1;
    private javax.swing.JButton JbNegativo2;
    private javax.swing.JButton JbNegativo3;
    private javax.swing.JLabel jLText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbAvancar;
    private javax.swing.JButton jbPositivo1;
    private javax.swing.JButton jbPositivo2;
    private javax.swing.JButton jbPositivo3;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlEnsino;
    private javax.swing.JLabel jlSisu;
    private javax.swing.JLabel jlSobreCurso;
    private javax.swing.JLabel jlSobreCurso1;
    private javax.swing.JTextArea taAreaA;
    private javax.swing.JTextArea taPontosN;
    private javax.swing.JTextArea taPontosP;
    // End of variables declaration//GEN-END:variables
}
