/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.BDPergunta;
import classes.Pergunta;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author Maria Heloisa Souza
 */
public class Etapa1_3 extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */  
    
    private String nome;
    private int cod_u; 

    public int getCod_u() {
        return cod_u;
    }

    public void setCod_u(int cod_u) {
        this.cod_u = cod_u;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }
    List<JCheckBox> checkboxes = new ArrayList<JCheckBox>();

    public Etapa1_3() {
        initComponents();
        Color vinho = new Color(66,0,0);
        this.getContentPane().setBackground(vinho);
        this.setLocationRelativeTo(null);
        
        checkboxes.add(jcPer1);
        checkboxes.add(jcPer2);
        checkboxes.add(jcPer3);
        checkboxes.add(jcPer4);
        checkboxes.add(jcPer5);
        checkboxes.add(jcPer6);
        checkboxes.add(jcPer7);
        checkboxes.add(jcPer8);
        checkboxes.add(jcPer9);
        checkboxes.add(jcPer10);
        checkboxes.add(jcPer11);
        checkboxes.add(jcPer12);
        checkboxes.add(jcPer13);
        checkboxes.add(jcPer14);
        checkboxes.add(jcPer15);
        checkboxes.add(jcPer16);
        checkboxes.add(jcPer17);
        checkboxes.add(jcPer18);
        checkboxes.add(jcPer19);
        checkboxes.add(jcPer20);
        checkboxes.add(jcPer21);
        checkboxes.add(jcPer22);
        checkboxes.add(jcPer23);
        checkboxes.add(jcPer24);
        checkboxes.add(jcPer25);
        
        BDPergunta bdp = new BDPergunta();
        ArrayList vetPer = bdp.buscaPerguntasEtapa1();
        Iterator it = vetPer.iterator();
        Pergunta p;
         for (int i=0,j=10; i<25; i++,j++) 
        {      
            p = (Pergunta)vetPer.get(j);
            checkboxes.get(i).setText(p.getDescricao()); 
        }
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAvancar = new javax.swing.JButton();
        jLText = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        painel = new javax.swing.JPanel();
        jcPer1 = new javax.swing.JCheckBox();
        jcPer4 = new javax.swing.JCheckBox();
        jcPer3 = new javax.swing.JCheckBox();
        jcPer11 = new javax.swing.JCheckBox();
        jcPer10 = new javax.swing.JCheckBox();
        jcPer6 = new javax.swing.JCheckBox();
        jcPer12 = new javax.swing.JCheckBox();
        jcPer13 = new javax.swing.JCheckBox();
        jcPer5 = new javax.swing.JCheckBox();
        jcPer8 = new javax.swing.JCheckBox();
        jcPer2 = new javax.swing.JCheckBox();
        jcPer7 = new javax.swing.JCheckBox();
        jcPer9 = new javax.swing.JCheckBox();
        jcPer14 = new javax.swing.JCheckBox();
        jcPer15 = new javax.swing.JCheckBox();
        jcPer16 = new javax.swing.JCheckBox();
        jcPer17 = new javax.swing.JCheckBox();
        jcPer18 = new javax.swing.JCheckBox();
        jcPer19 = new javax.swing.JCheckBox();
        jcPer20 = new javax.swing.JCheckBox();
        jcPer21 = new javax.swing.JCheckBox();
        jcPer22 = new javax.swing.JCheckBox();
        jcPer23 = new javax.swing.JCheckBox();
        jcPer24 = new javax.swing.JCheckBox();
        jcPer25 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Etapa1_3");
        setBackground(new java.awt.Color(66, 0, 0));
        setSize(945, 512);

        jbAvancar.setBackground(new java.awt.Color(153, 102, 51));
        jbAvancar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbAvancar.setForeground(new java.awt.Color(255, 255, 255));
        jbAvancar.setText("Avançar");
        jbAvancar.setToolTipText("");
        jbAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAvancarActionPerformed(evt);
            }
        });

        jLText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLText.setForeground(new java.awt.Color(255, 255, 255));
        jLText.setText("Selecione as coisas que gosta de fazer, suas aptidões e habilidades que considere ter:");

        jbVoltar.setBackground(new java.awt.Color(153, 102, 51));
        jbVoltar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jbVoltar.setText("Voltar");
        jbVoltar.setToolTipText("");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        painel.setBackground(new java.awt.Color(255, 255, 255));
        painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 51, 25), 6));

        jcPer1.setBackground(new java.awt.Color(255, 255, 255));
        jcPer1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer1.setForeground(new java.awt.Color(66, 0, 0));
        jcPer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPer1ActionPerformed(evt);
            }
        });

        jcPer4.setBackground(new java.awt.Color(255, 255, 255));
        jcPer4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer4.setForeground(new java.awt.Color(66, 0, 0));

        jcPer3.setBackground(new java.awt.Color(255, 255, 255));
        jcPer3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer3.setForeground(new java.awt.Color(66, 0, 0));
        jcPer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPer3ActionPerformed(evt);
            }
        });

        jcPer11.setBackground(new java.awt.Color(255, 255, 255));
        jcPer11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer11.setForeground(new java.awt.Color(60, 0, 0));
        jcPer11.setMnemonic('0');
        jcPer11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPer11ActionPerformed(evt);
            }
        });

        jcPer10.setBackground(new java.awt.Color(255, 255, 255));
        jcPer10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer10.setForeground(new java.awt.Color(66, 0, 0));

        jcPer6.setBackground(new java.awt.Color(255, 255, 255));
        jcPer6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer6.setForeground(new java.awt.Color(66, 0, 0));
        jcPer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPer6ActionPerformed(evt);
            }
        });

        jcPer12.setBackground(new java.awt.Color(255, 255, 255));
        jcPer12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer12.setForeground(new java.awt.Color(66, 0, 0));

        jcPer13.setBackground(new java.awt.Color(255, 255, 255));
        jcPer13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer13.setForeground(new java.awt.Color(66, 0, 0));

        jcPer5.setBackground(new java.awt.Color(255, 255, 255));
        jcPer5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer5.setForeground(new java.awt.Color(66, 0, 0));

        jcPer8.setBackground(new java.awt.Color(255, 255, 255));
        jcPer8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer8.setForeground(new java.awt.Color(66, 0, 0));

        jcPer2.setBackground(new java.awt.Color(255, 255, 255));
        jcPer2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer2.setForeground(new java.awt.Color(66, 0, 0));

        jcPer7.setBackground(new java.awt.Color(255, 255, 255));
        jcPer7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer7.setForeground(new java.awt.Color(66, 0, 0));

        jcPer9.setBackground(new java.awt.Color(255, 255, 255));
        jcPer9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer9.setForeground(new java.awt.Color(66, 0, 0));

        jcPer14.setBackground(new java.awt.Color(255, 255, 255));
        jcPer14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer14.setForeground(new java.awt.Color(66, 0, 0));

        jcPer15.setBackground(new java.awt.Color(255, 255, 255));
        jcPer15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer15.setForeground(new java.awt.Color(66, 0, 0));

        jcPer16.setBackground(new java.awt.Color(255, 255, 255));
        jcPer16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer16.setForeground(new java.awt.Color(66, 0, 0));

        jcPer17.setBackground(new java.awt.Color(255, 255, 255));
        jcPer17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer17.setForeground(new java.awt.Color(66, 0, 0));

        jcPer18.setBackground(new java.awt.Color(255, 255, 255));
        jcPer18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer18.setForeground(new java.awt.Color(66, 0, 0));

        jcPer19.setBackground(new java.awt.Color(255, 255, 255));
        jcPer19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer19.setForeground(new java.awt.Color(66, 0, 0));

        jcPer20.setBackground(new java.awt.Color(255, 255, 255));
        jcPer20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer20.setForeground(new java.awt.Color(66, 0, 0));

        jcPer21.setBackground(new java.awt.Color(255, 255, 255));
        jcPer21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer21.setForeground(new java.awt.Color(66, 0, 0));

        jcPer22.setBackground(new java.awt.Color(255, 255, 255));
        jcPer22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer22.setForeground(new java.awt.Color(66, 0, 0));

        jcPer23.setBackground(new java.awt.Color(255, 255, 255));
        jcPer23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer23.setForeground(new java.awt.Color(66, 0, 0));

        jcPer24.setBackground(new java.awt.Color(255, 255, 255));
        jcPer24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer24.setForeground(new java.awt.Color(66, 0, 0));

        jcPer25.setBackground(new java.awt.Color(255, 255, 255));
        jcPer25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcPer25.setForeground(new java.awt.Color(66, 0, 0));

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcPer8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcPer25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jcPer1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcPer25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(painel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAvancar)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLText)
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAvancar)
                    .addComponent(jbVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcPer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPer3ActionPerformed

    private void jcPer11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPer11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPer11ActionPerformed

    private void jcPer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPer6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPer6ActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
           Etapa1_2 p = new Etapa1_2();
           p.setCod_u(cod_u);
           p.setCod_u(cod_u);
           p.setNome(nome);
            p.setVisible(true);
            p.setLocationRelativeTo(null);
            dispose();        
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAvancarActionPerformed
            Etapa1_4 p = new Etapa1_4();
            p.setNome(nome);
            p.setVisible(true);
            p.setLocationRelativeTo(null);
            dispose();        
    }//GEN-LAST:event_jbAvancarActionPerformed

    private void jcPer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etapa1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etapa1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etapa1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etapa1_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etapa1_3().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAvancar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JCheckBox jcPer1;
    private javax.swing.JCheckBox jcPer10;
    private javax.swing.JCheckBox jcPer11;
    private javax.swing.JCheckBox jcPer12;
    private javax.swing.JCheckBox jcPer13;
    private javax.swing.JCheckBox jcPer14;
    private javax.swing.JCheckBox jcPer15;
    private javax.swing.JCheckBox jcPer16;
    private javax.swing.JCheckBox jcPer17;
    private javax.swing.JCheckBox jcPer18;
    private javax.swing.JCheckBox jcPer19;
    private javax.swing.JCheckBox jcPer2;
    private javax.swing.JCheckBox jcPer20;
    private javax.swing.JCheckBox jcPer21;
    private javax.swing.JCheckBox jcPer22;
    private javax.swing.JCheckBox jcPer23;
    private javax.swing.JCheckBox jcPer24;
    private javax.swing.JCheckBox jcPer25;
    private javax.swing.JCheckBox jcPer3;
    private javax.swing.JCheckBox jcPer4;
    private javax.swing.JCheckBox jcPer5;
    private javax.swing.JCheckBox jcPer6;
    private javax.swing.JCheckBox jcPer7;
    private javax.swing.JCheckBox jcPer8;
    private javax.swing.JCheckBox jcPer9;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
