/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.BDusuario;
import java.awt.Color;

/**
 *
 * @author Maria Heloisa Souza
 */
public class PainelAtividades extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
     private String nome; 
     private int cod_u; 

    public int getCod_u() {
        return cod_u;
    }

    public void setCod_u(int cod_u) {
        this.cod_u = cod_u;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }
     public void Nome(String nome){
      user2.setText("Bem Vindo "+nome);
    }
    public PainelAtividades() {
        initComponents();
        Color vinho = new Color(66,0,0);
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        
    }
     
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbAtividade1 = new javax.swing.JButton();
        jbAtividade2 = new javax.swing.JButton();
        Atividade3 = new javax.swing.JButton();
        jbAtividade5 = new javax.swing.JButton();
        jbAtividade4 = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        user2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atividades");
        setBackground(new java.awt.Color(66, 0, 0));
        setMinimumSize(new java.awt.Dimension(910, 519));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);

        jbAtividade1.setBackground(new java.awt.Color(66, 0, 0));
        jbAtividade1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbAtividade1.setForeground(new java.awt.Color(255, 255, 255));
        jbAtividade1.setText("Atividade 1");
        jbAtividade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtividade1ActionPerformed(evt);
            }
        });

        jbAtividade2.setBackground(new java.awt.Color(66, 0, 0));
        jbAtividade2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbAtividade2.setForeground(new java.awt.Color(255, 255, 255));
        jbAtividade2.setText("Atividade 2");
        jbAtividade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtividade2ActionPerformed(evt);
            }
        });

        Atividade3.setBackground(new java.awt.Color(66, 0, 0));
        Atividade3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Atividade3.setForeground(new java.awt.Color(255, 255, 255));
        Atividade3.setText("Atividade 3");
        Atividade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atividade3ActionPerformed(evt);
            }
        });

        jbAtividade5.setBackground(new java.awt.Color(66, 0, 0));
        jbAtividade5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbAtividade5.setForeground(new java.awt.Color(255, 255, 255));
        jbAtividade5.setText("Atividade 5");
        jbAtividade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtividade5ActionPerformed(evt);
            }
        });

        jbAtividade4.setBackground(new java.awt.Color(66, 0, 0));
        jbAtividade4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbAtividade4.setForeground(new java.awt.Color(255, 255, 255));
        jbAtividade4.setText("Atividade 4");
        jbAtividade4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtividade4ActionPerformed(evt);
            }
        });

        jbSair.setBackground(new java.awt.Color(66, 0, 0));
        jbSair.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbSair.setForeground(new java.awt.Color(255, 255, 255));
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        user2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        user2.setForeground(new java.awt.Color(60, 0, 0));
        user2.setText("BemVindo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(Atividade3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jbAtividade4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jbAtividade5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbAtividade1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jbAtividade2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAtividade1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtividade2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAtividade4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Atividade3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtividade5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(jbSair))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAtividade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtividade2ActionPerformed
        // TODO add your handling code here:
     Etapa2_1 e = new Etapa2_1();
     e.setCod_u(cod_u);
     e.setCod_u(cod_u);
     e.setNome(nome);
     e.setVisible(true);
     e.setLocationRelativeTo(null);
     dispose();
    }//GEN-LAST:event_jbAtividade2ActionPerformed

    private void Atividade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atividade3ActionPerformed
     Etapa3_1 e = new Etapa3_1();
     e.setNome(nome);
     e.setVisible(true);
     e.setLocationRelativeTo(null);
     dispose();
    }//GEN-LAST:event_Atividade3ActionPerformed

    private void jbAtividade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtividade4ActionPerformed
     Etapa4 e = new Etapa4();
     e.setNome(nome);
     System.out.println(cod_u);
     e.setCod_u(cod_u);
     e.men(cod_u);
     e.setVisible(true);
     e.setLocationRelativeTo(null);
     dispose();        
    }//GEN-LAST:event_jbAtividade4ActionPerformed

    private void jbAtividade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtividade5ActionPerformed
     Etapa5 e = new Etapa5();
     e.setCod_u(cod_u);
     e.setNome(nome);
     e.setVisible(true);
     e.setLocationRelativeTo(null);
     dispose();
    }//GEN-LAST:event_jbAtividade5ActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        PainelPrincipal p = new PainelPrincipal();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbAtividade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtividade1ActionPerformed
        Etapa1_1 e = new Etapa1_1();
        e.setCod_u(cod_u);
        e.setNome(nome);
        e.setVisible(true);
        e.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jbAtividade1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelAtividades().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atividade3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAtividade1;
    private javax.swing.JButton jbAtividade2;
    private javax.swing.JButton jbAtividade4;
    private javax.swing.JButton jbAtividade5;
    private javax.swing.JButton jbSair;
    public javax.swing.JLabel user2;
    // End of variables declaration//GEN-END:variables
}
