/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.BDAdministrador;
import bd.BDpsicologo;
import bd.BDusuario;
import java.awt.Color;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria Heloisa Souza
 */
public class PainelPrincipal extends javax.swing.JFrame {

    public PainelPrincipal() {
        initComponents();

        /*Color cor = new Color(77,51,25);
        this.getContentPane().setBackground(cor);*/
        String texto = "<html>"
                + "<font size='6' color='#ffc61a'><strong><center>Meu Curso - Orientação Vocacional</center></strong></font>"
                + "<br><br><font size='4' color='white'>    Seja bem vindo! Ajudaremos você a decidir o seu curso."
                + " Nosso objetivo é fornecer informações e propôr atividades para auxiliá-lo em seu"
                + " autoconhecimento, interesses, gostos e aptidões, para assim permitir uma análise mais clara"
                + " e uma decisão mais precisa.</font>"
                + "</html>";

        jLabel2.setText(texto);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jbSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        painel38 = new javax.swing.JPanel();
        imgLog38 = new javax.swing.JLabel();
        jlPer38 = new javax.swing.JLabel();
        jlEmail38 = new javax.swing.JLabel();
        jlSenha38 = new javax.swing.JLabel();
        jbCancelar38 = new javax.swing.JButton();
        jbLogar38 = new javax.swing.JButton();
        jtEmail38 = new javax.swing.JTextField();
        jtSenha38 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        painel37 = new javax.swing.JPanel();
        imgLog37 = new javax.swing.JLabel();
        jlPer37 = new javax.swing.JLabel();
        jlEmail37 = new javax.swing.JLabel();
        jlSenha37 = new javax.swing.JLabel();
        jbCancelar37 = new javax.swing.JButton();
        jbLogar37 = new javax.swing.JButton();
        jtEmail37 = new javax.swing.JTextField();
        jtSenha37 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        painel36 = new javax.swing.JPanel();
        imgCad = new javax.swing.JLabel();
        jlCad = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtEmail36 = new javax.swing.JTextField();
        jlEmail36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpSenha = new javax.swing.JPasswordField();
        jbCancelar36 = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        painel44 = new javax.swing.JPanel();
        imgLog36 = new javax.swing.JLabel();
        jlPer36 = new javax.swing.JLabel();
        jlEmail44 = new javax.swing.JLabel();
        jlSenha36 = new javax.swing.JLabel();
        jbCancelar44 = new javax.swing.JButton();
        jbLoginpis = new javax.swing.JButton();
        jtEmail44 = new javax.swing.JTextField();
        jpSenha1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 102, 51));

        jPanel5.setBackground(new java.awt.Color(66, 0, 0));

        jbSair.setBackground(new java.awt.Color(153, 102, 51));
        jbSair.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbSair.setForeground(new java.awt.Color(255, 255, 255));
        jbSair.setText("Sair");
        jbSair.setToolTipText("");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(847, Short.MAX_VALUE)
                .addComponent(jbSair)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jbSair)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Início", jPanel5);

        jPanel1.setBackground(new java.awt.Color(66, 0, 0));

        painel38.setBackground(new java.awt.Color(255, 255, 255));
        painel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 51, 25), 6));

        imgLog38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/icons8-usuário-100 (2).png"))); // NOI18N

        jlPer38.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlPer38.setForeground(new java.awt.Color(66, 0, 0));
        jlPer38.setText("Login Administradores");

        jlEmail38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlEmail38.setForeground(new java.awt.Color(66, 0, 0));
        jlEmail38.setText("Login:");

        jlSenha38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSenha38.setForeground(new java.awt.Color(66, 0, 0));
        jlSenha38.setText("Senha:");

        jbCancelar38.setBackground(new java.awt.Color(153, 102, 51));
        jbCancelar38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbCancelar38.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar38.setLabel("Cancelar");
        jbCancelar38.setMaximumSize(new java.awt.Dimension(70, 25));
        jbCancelar38.setMinimumSize(new java.awt.Dimension(70, 25));
        jbCancelar38.setPreferredSize(new java.awt.Dimension(88, 25));
        jbCancelar38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar38ActionPerformed(evt);
            }
        });

        jbLogar38.setBackground(new java.awt.Color(153, 102, 51));
        jbLogar38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbLogar38.setForeground(new java.awt.Color(255, 255, 255));
        jbLogar38.setText("Logar");
        jbLogar38.setToolTipText("");
        jbLogar38.setPreferredSize(new java.awt.Dimension(88, 25));
        jbLogar38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogar38ActionPerformed(evt);
            }
        });

        jtEmail38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtEmail38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmail38ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel38Layout = new javax.swing.GroupLayout(painel38);
        painel38.setLayout(painel38Layout);
        painel38Layout.setHorizontalGroup(
            painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel38Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLog38)
                .addGap(141, 141, 141))
            .addGroup(painel38Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel38Layout.createSequentialGroup()
                        .addComponent(jlPer38)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painel38Layout.createSequentialGroup()
                        .addGroup(painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel38Layout.createSequentialGroup()
                                .addGroup(painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlSenha38, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(jlEmail38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtEmail38)
                                    .addComponent(jtSenha38)))
                            .addGroup(painel38Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jbCancelar38, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbLogar38, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 5, Short.MAX_VALUE)))
                        .addGap(79, 79, 79))))
        );
        painel38Layout.setVerticalGroup(
            painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel38Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(imgLog38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPer38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEmail38, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtEmail38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha38)
                    .addComponent(jtSenha38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(painel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLogar38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(painel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(painel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jTabbedPane1.addTab("Administradores", jPanel1);

        jPanel2.setBackground(new java.awt.Color(66, 0, 0));

        painel37.setBackground(new java.awt.Color(255, 255, 255));
        painel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 51, 25), 6));

        imgLog37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/icons8-usuário-100 (2).png"))); // NOI18N

        jlPer37.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlPer37.setForeground(new java.awt.Color(66, 0, 0));
        jlPer37.setText("Login");

        jlEmail37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlEmail37.setForeground(new java.awt.Color(66, 0, 0));
        jlEmail37.setText("Email:");

        jlSenha37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSenha37.setForeground(new java.awt.Color(66, 0, 0));
        jlSenha37.setText("Senha:");

        jbCancelar37.setBackground(new java.awt.Color(153, 102, 51));
        jbCancelar37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbCancelar37.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar37.setLabel("Cancelar");
        jbCancelar37.setMaximumSize(new java.awt.Dimension(70, 25));
        jbCancelar37.setMinimumSize(new java.awt.Dimension(70, 25));
        jbCancelar37.setPreferredSize(new java.awt.Dimension(88, 25));
        jbCancelar37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar37ActionPerformed(evt);
            }
        });

        jbLogar37.setBackground(new java.awt.Color(153, 102, 51));
        jbLogar37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbLogar37.setForeground(new java.awt.Color(255, 255, 255));
        jbLogar37.setText("Logar");
        jbLogar37.setToolTipText("");
        jbLogar37.setPreferredSize(new java.awt.Dimension(88, 25));
        jbLogar37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogar37ActionPerformed(evt);
            }
        });

        jtEmail37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtEmail37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmail37ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel37Layout = new javax.swing.GroupLayout(painel37);
        painel37.setLayout(painel37Layout);
        painel37Layout.setHorizontalGroup(
            painel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel37Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(painel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlEmail37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSenha37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtEmail37)
                    .addComponent(jtSenha37))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel37Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(painel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel37Layout.createSequentialGroup()
                        .addComponent(jlPer37)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel37Layout.createSequentialGroup()
                        .addComponent(imgLog37)
                        .addGap(141, 141, 141))))
            .addGroup(painel37Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jbCancelar37, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLogar37, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel37Layout.setVerticalGroup(
            painel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel37Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(imgLog37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPer37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEmail37, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtEmail37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha37)
                    .addComponent(jtSenha37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(painel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLogar37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(painel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(painel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jTabbedPane1.addTab("Login", jPanel2);

        jPanel3.setBackground(new java.awt.Color(66, 0, 0));

        painel36.setBackground(new java.awt.Color(255, 255, 255));
        painel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 51, 25), 6));

        imgCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/icons8-usuário-100 (1).png"))); // NOI18N

        jlCad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlCad.setForeground(new java.awt.Color(66, 0, 0));
        jlCad.setText("Cadastro");

        jlNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNome.setForeground(new java.awt.Color(66, 0, 0));
        jlNome.setText("Nome completo:");

        jtEmail36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmail36ActionPerformed(evt);
            }
        });

        jlEmail36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlEmail36.setForeground(new java.awt.Color(66, 0, 0));
        jlEmail36.setText("Email:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 0, 0));
        jLabel1.setText("Senha:");

        jpSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpSenhaActionPerformed(evt);
            }
        });

        jbCancelar36.setBackground(new java.awt.Color(153, 102, 51));
        jbCancelar36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbCancelar36.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar36.setLabel("Cancelar");
        jbCancelar36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar36ActionPerformed(evt);
            }
        });

        jbCadastrar.setBackground(new java.awt.Color(153, 102, 51));
        jbCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.setToolTipText("");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel36Layout = new javax.swing.GroupLayout(painel36);
        painel36.setLayout(painel36Layout);
        painel36Layout.setHorizontalGroup(
            painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel36Layout.createSequentialGroup()
                .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel36Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painel36Layout.createSequentialGroup()
                                .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlEmail36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtEmail36)
                                    .addComponent(jpSenha)))
                            .addGroup(painel36Layout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addGap(2, 2, 2)
                                .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNome)
                                    .addGroup(painel36Layout.createSequentialGroup()
                                        .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlCad)
                                            .addComponent(imgCad))
                                        .addGap(0, 74, Short.MAX_VALUE))))))
                    .addGroup(painel36Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jbCancelar36)
                        .addGap(18, 18, 18)
                        .addComponent(jbCadastrar)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        painel36Layout.setVerticalGroup(
            painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgCad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlEmail36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtEmail36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar36)
                    .addComponent(jbCadastrar))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(painel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jTabbedPane1.addTab("Cadastro", jPanel3);

        jPanel4.setBackground(new java.awt.Color(66, 0, 0));

        painel44.setBackground(new java.awt.Color(255, 255, 255));
        painel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 51, 25), 6));

        imgLog36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/icons8-psicologia-filled-100.png"))); // NOI18N

        jlPer36.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlPer36.setForeground(new java.awt.Color(66, 0, 0));
        jlPer36.setText("Login Psicólogo");

        jlEmail44.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlEmail44.setForeground(new java.awt.Color(66, 0, 0));
        jlEmail44.setText("Nome:");

        jlSenha36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSenha36.setForeground(new java.awt.Color(66, 0, 0));
        jlSenha36.setText("Senha:");

        jbCancelar44.setBackground(new java.awt.Color(153, 102, 51));
        jbCancelar44.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbCancelar44.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar44.setLabel("Cancelar");
        jbCancelar44.setMaximumSize(new java.awt.Dimension(70, 25));
        jbCancelar44.setMinimumSize(new java.awt.Dimension(70, 25));
        jbCancelar44.setPreferredSize(new java.awt.Dimension(88, 25));
        jbCancelar44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar44ActionPerformed(evt);
            }
        });

        jbLoginpis.setBackground(new java.awt.Color(153, 102, 51));
        jbLoginpis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbLoginpis.setForeground(new java.awt.Color(255, 255, 255));
        jbLoginpis.setText("Logar");
        jbLoginpis.setToolTipText("");
        jbLoginpis.setPreferredSize(new java.awt.Dimension(88, 25));
        jbLoginpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginpisActionPerformed(evt);
            }
        });

        jtEmail44.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtEmail44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmail44ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel44Layout = new javax.swing.GroupLayout(painel44);
        painel44.setLayout(painel44Layout);
        painel44Layout.setHorizontalGroup(
            painel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel44Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(painel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlEmail44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSenha36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtEmail44)
                    .addComponent(jpSenha1))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel44Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(painel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel44Layout.createSequentialGroup()
                        .addComponent(imgLog36)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel44Layout.createSequentialGroup()
                        .addComponent(jlPer36)
                        .addGap(111, 111, 111))))
            .addGroup(painel44Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jbCancelar44, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLoginpis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel44Layout.setVerticalGroup(
            painel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel44Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(imgLog36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPer36)
                .addGap(9, 9, 9)
                .addGroup(painel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEmail44, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtEmail44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha36)
                    .addComponent(jpSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLoginpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(painel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(painel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jTabbedPane1.addTab("Psicólogos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelar37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar37ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jbCancelar37ActionPerformed

    private void jbLogar37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogar37ActionPerformed
        String email = jtEmail37.getText();
        String senha = new String(jtSenha37.getPassword());
        BDusuario bd = new BDusuario();
        int codigo = -1;
        try { // faz a busca no BD
            codigo = bd.verificaUsuario(email, senha);
        } catch (InstantiationException ex) {
            System.err.println(ex);
        }
        if (codigo != -1) {   // Administrador do sistema
            // limpa os dados
            jtSenha37.setText("");
            jtEmail37.setText("");
            dispose();
            PainelAtividades obj = new PainelAtividades();
            String nome=bd.getGlobal();
            obj.Nome(nome);
            obj.setCod_u(codigo);
            obj.setNome(nome);
            obj.setVisible(this.rootPaneCheckingEnabled);

        } else { // Usuário não cadastrado
            JOptionPane.showMessageDialog(rootPane, "Usuário não cadastrado",
                    "Alerta de erro", JOptionPane.ERROR_MESSAGE);
            // Volta o cursor para o campo código
            jtSenha37.setText("");
            jtEmail37.selectAll();
            jtEmail37.requestFocusInWindow();
        }
    }//GEN-LAST:event_jbLogar37ActionPerformed

    private void jtEmail37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmail37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmail37ActionPerformed

    private void jbCancelar36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar36ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jbCancelar36ActionPerformed

    private void jbCancelar44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar44ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jbCancelar44ActionPerformed

    private void jbLoginpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginpisActionPerformed
        String login = jtEmail44.getText();
        String senha = new String(jpSenha1.getPassword());
        BDpsicologo bd = new BDpsicologo();
        int codigo = -1;
        try { // faz a busca no BD
            codigo = bd.verificaPsicologo(login, senha);
        } catch (InstantiationException ex) {
            System.err.println(ex);
        }
        if (codigo != -1) {   // Administrador do sistema
            // limpa os dados
            jtSenha37.setText("");
            jtEmail37.setText("");
            dispose();
            PainelPsicologo obj = new PainelPsicologo();
            obj.Psi(login);
            obj.setVisible(this.rootPaneCheckingEnabled);

        } else { // Usuário não cadastrado
            JOptionPane.showMessageDialog(rootPane, "Usuário não cadastrado",
                    "Alerta de erro", JOptionPane.ERROR_MESSAGE);
            // Volta o cursor para o campo código
            jtSenha37.setText("");
            jtEmail37.selectAll();
            jtEmail37.requestFocusInWindow();
        }

    }//GEN-LAST:event_jbLoginpisActionPerformed

    private void jtEmail44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmail44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmail44ActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        String nome = "", senha = "", email = "";
        nome = jtNome.getText();
        email = jtEmail36.getText();
        senha = new String(jpSenha.getPassword());
        Perfil objperfil = new Perfil(nome, email, senha);
        Pattern p = Pattern.compile(".+@.+\\.[a-z]+");
        Matcher m = p.matcher(email);
        boolean matchFound = m.matches();

        if (!matchFound) {
            JOptionPane.showMessageDialog(null, "E-mail inválido!\nAdicione '@' e tente novamente");
        } else {
            objperfil.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jtEmail36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmail36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmail36ActionPerformed

    private void jpSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpSenhaActionPerformed

    private void jbCancelar38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar38ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jbCancelar38ActionPerformed

    private void jbLogar38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogar38ActionPerformed
        String login = "", senha = "";
        login = jtEmail38.getText();
        senha = new String(jtSenha38.getPassword());
        BDAdministrador bd = new BDAdministrador();
        int codigo = -1;
        try { // faz a busca no BD
            codigo = bd.verificaAdministrado(login, senha);
        } catch (InstantiationException ex) {
            System.err.println(ex);
        }
        if (codigo != -1) {   // Administrador do sistema
            // limpa os dados
            jtSenha38.setText("");
            jtEmail38.setText("");
            dispose();
            PainelAdministrador obj = new PainelAdministrador();
            obj.Adm(login);
            obj.setVisible(this.rootPaneCheckingEnabled);

        } else { // Administrador não cadastrado
            JOptionPane.showMessageDialog(rootPane, "Usuário não cadastrado",
                    "Alerta de erro", JOptionPane.ERROR_MESSAGE);
            // Volta o cursor para o campo código
            jtSenha38.setText("");
            jtEmail38.selectAll();
            jtEmail38.requestFocusInWindow();
        }

    }//GEN-LAST:event_jbLogar38ActionPerformed

    private void jtEmail38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmail38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmail38ActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgCad;
    private javax.swing.JLabel imgLog36;
    private javax.swing.JLabel imgLog37;
    private javax.swing.JLabel imgLog38;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar36;
    private javax.swing.JButton jbCancelar37;
    private javax.swing.JButton jbCancelar38;
    private javax.swing.JButton jbCancelar44;
    private javax.swing.JButton jbLogar37;
    private javax.swing.JButton jbLogar38;
    private javax.swing.JButton jbLoginpis;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel jlCad;
    private javax.swing.JLabel jlEmail36;
    private javax.swing.JLabel jlEmail37;
    private javax.swing.JLabel jlEmail38;
    private javax.swing.JLabel jlEmail44;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPer36;
    private javax.swing.JLabel jlPer37;
    private javax.swing.JLabel jlPer38;
    private javax.swing.JLabel jlSenha36;
    private javax.swing.JLabel jlSenha37;
    private javax.swing.JLabel jlSenha38;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JPasswordField jpSenha1;
    private javax.swing.JTextField jtEmail36;
    private javax.swing.JTextField jtEmail37;
    private javax.swing.JTextField jtEmail38;
    private javax.swing.JTextField jtEmail44;
    private javax.swing.JTextField jtNome;
    private javax.swing.JPasswordField jtSenha37;
    private javax.swing.JPasswordField jtSenha38;
    private javax.swing.JPanel painel36;
    private javax.swing.JPanel painel37;
    private javax.swing.JPanel painel38;
    private javax.swing.JPanel painel44;
    // End of variables declaration//GEN-END:variables
}
