/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.BDPsi_usuario;
import bd.BDusuario;
import classes.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria Heloisa Souza
 */
public class PainelPsicologo extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
     private int codigo;
     private String nome;
     public void Psi(String psi){
      nome=psi;   
      jlNomeP.setText("Bem Vindo "+psi);
      jlNomeP1.setText("Bem Vindo "+psi);
      jlNomeP2.setText("Bem Vindo "+psi);
    }
    public PainelPsicologo() {
        initComponents();
        Color vinho = new Color(66,0,0);
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        jPanel2.setVisible(true);
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        
        BDusuario bd = new BDusuario();
        ArrayList vetUser = bd.buscaUser();
        Iterator it = vetUser.iterator();
        Usuario U; 
        while( it.hasNext() ){ 
            U = (Usuario)it.next(); 
            cbAluno.addItem( U.getNome()); 
            cbAluno1.addItem( U.getNome()); 
        }
        cbAluno.setMaximumRowCount( 10 ); 
        cbAluno1.setMaximumRowCount( 10 ); 
        cbAluno.setSelectedIndex(0);  
        cbAluno1.setSelectedIndex(0);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbAcomp = new javax.swing.JButton();
        jbLaudo = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jlNomeP2 = new javax.swing.JLabel();
        painel5 = new javax.swing.JPanel();
        jbEnviar5 = new javax.swing.JButton();
        jbCancelar5 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtaMenssage5 = new javax.swing.JTextArea();
        jlNomeU4 = new javax.swing.JLabel();
        cbAluno1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jtaMenssage6 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jlNomeP = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlNomeP1 = new javax.swing.JLabel();
        jlNomeU3 = new javax.swing.JLabel();
        cbAluno = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Psicólogo");
        setBackground(new java.awt.Color(66, 0, 0));
        setMinimumSize(new java.awt.Dimension(910, 519));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAcomp.setBackground(new java.awt.Color(66, 0, 0));
        jbAcomp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbAcomp.setForeground(new java.awt.Color(255, 255, 255));
        jbAcomp.setText("<html><center>Acompanhar Alunos </center></html>");
        jbAcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcompActionPerformed(evt);
            }
        });
        jPanel1.add(jbAcomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 189, 71));

        jbLaudo.setBackground(new java.awt.Color(66, 0, 0));
        jbLaudo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbLaudo.setForeground(new java.awt.Color(255, 255, 255));
        jbLaudo.setText("Emitir Laudo");
        jbLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLaudoActionPerformed(evt);
            }
        });
        jPanel1.add(jbLaudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 189, 71));

        jbSair.setBackground(new java.awt.Color(66, 0, 0));
        jbSair.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbSair.setForeground(new java.awt.Color(255, 255, 255));
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        jPanel1.add(jbSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 308, 81, -1));

        jlNomeP2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNomeP2.setForeground(new java.awt.Color(66, 0, 0));
        jlNomeP2.setText("Bem Vindo [Nome Psicólogo]");

        painel5.setBackground(new java.awt.Color(255, 255, 255));
        painel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 51, 25), 6));

        jbEnviar5.setBackground(new java.awt.Color(153, 102, 51));
        jbEnviar5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbEnviar5.setForeground(new java.awt.Color(255, 255, 255));
        jbEnviar5.setText("Enviar");
        jbEnviar5.setToolTipText("");
        jbEnviar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviar5ActionPerformed(evt);
            }
        });

        jbCancelar5.setBackground(new java.awt.Color(153, 102, 51));
        jbCancelar5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbCancelar5.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar5.setText("Cancelar");
        jbCancelar5.setToolTipText("");
        jbCancelar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar5ActionPerformed(evt);
            }
        });

        jtaMenssage5.setColumns(20);
        jtaMenssage5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtaMenssage5.setForeground(new java.awt.Color(66, 0, 0));
        jtaMenssage5.setRows(5);
        jtaMenssage5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 51, 25), 2));
        jScrollPane11.setViewportView(jtaMenssage5);

        jlNomeU4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNomeU4.setForeground(new java.awt.Color(66, 0, 0));
        jlNomeU4.setText("Selecione o aluno para fazer o laudo:");

        cbAluno1.setBackground(new java.awt.Color(153, 102, 51));
        cbAluno1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbAluno1.setForeground(new java.awt.Color(66, 0, 0));
        cbAluno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAluno1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 0, 0));
        jLabel1.setText("Digite aqui:");

        jtaMenssage6.setColumns(20);
        jtaMenssage6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtaMenssage6.setForeground(new java.awt.Color(66, 0, 0));
        jtaMenssage6.setRows(5);
        jtaMenssage6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 51, 25), 2));
        jScrollPane12.setViewportView(jtaMenssage6);

        javax.swing.GroupLayout painel5Layout = new javax.swing.GroupLayout(painel5);
        painel5.setLayout(painel5Layout);
        painel5Layout.setHorizontalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel5Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel5Layout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addComponent(jbCancelar5)
                        .addGap(18, 18, 18)
                        .addComponent(jbEnviar5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(painel5Layout.createSequentialGroup()
                        .addGroup(painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlNomeU4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbAluno1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painel5Layout.setVerticalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlNomeU4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar5)
                    .addComponent(jbEnviar5))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlNomeP2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNomeP2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 670, 480));

        jlNomeP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNomeP.setForeground(new java.awt.Color(66, 0, 0));
        jlNomeP.setText("Bem Vindo [Nome Psicólogo]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNomeP)
                .addContainerGap(483, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 670, 470));

        jlNomeP1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNomeP1.setForeground(new java.awt.Color(66, 0, 0));
        jlNomeP1.setText("Bem Vindo [Nome Psicólogo]");

        jlNomeU3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNomeU3.setForeground(new java.awt.Color(66, 0, 0));
        jlNomeU3.setText("Selecione o aluno que deseja acompanhar:");

        cbAluno.setBackground(new java.awt.Color(153, 102, 51));
        cbAluno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbAluno.setForeground(new java.awt.Color(66, 0, 0));
        cbAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlNomeP1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 195, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNomeU3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNomeP1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jlNomeU3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 670, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAcompActionPerformed
        jPanel2.setVisible(false);
        jPanel4.setVisible(false);
        jPanel3.setVisible(true);    }//GEN-LAST:event_jbAcompActionPerformed

    private void jbLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLaudoActionPerformed
        jPanel4.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jbLaudoActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        PainelPrincipal p = new PainelPrincipal();
        p.setVisible(true);
        p.setLocationRelativeTo(null);       
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void cbAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlunoActionPerformed
      
    }//GEN-LAST:event_cbAlunoActionPerformed

    private void jbEnviar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviar5ActionPerformed
        String  mensagem= "";
        int  link_aluno,link_psi=1;
         
        mensagem=jtaMenssage6.getText();

        Psicologo_usuario objP = new Psicologo_usuario(codigo, link_psi, mensagem, nome);
        BDPsi_usuario objBD = new BDPsi_usuario();

        if (objBD.insereMensagem(objP)) {
            JOptionPane.showMessageDialog(rootPane, "Dados gravados com sucesso",
                    "Confirmação de cadastro", JOptionPane.INFORMATION_MESSAGE);
        BDPsi_usuario bd = new BDPsi_usuario();    
        ArrayList vetMen = bd.buscaMensagem(codigo);
        Iterator it = vetMen.iterator();
        Psicologo_usuario P;
        String men = "";
        while (it.hasNext()) {
            P = (Psicologo_usuario) it.next();
            men += P.getNome() + " - " + P.getMensagem() + "\n";
        }
        jtaMenssage5.setText(men);
        jtaMenssage6.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário já existente.",
                    "Alerta de erro", JOptionPane.ERROR_MESSAGE);
        }  

    }//GEN-LAST:event_jbEnviar5ActionPerformed

    private void jbCancelar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar5ActionPerformed
        
    }//GEN-LAST:event_jbCancelar5ActionPerformed

    private void cbAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAluno1ActionPerformed
        String nome = cbAluno1.getSelectedItem().toString();

        BDusuario u = new BDusuario();
        int cod_u = u.buscaCodUse(nome);
        codigo=cod_u;
        BDPsi_usuario bd = new BDPsi_usuario();
        ArrayList vetMen = bd.buscaMensagem(cod_u);
        Iterator it = vetMen.iterator();
        Psicologo_usuario P;
        String mensagem = "";
        while (it.hasNext()) {
            P = (Psicologo_usuario) it.next();
            mensagem += P.getNome() + " - " + P.getMensagem() + "\n";
        }
        jtaMenssage5.setText(mensagem);
    }//GEN-LAST:event_cbAluno1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelPsicologo().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAluno;
    private javax.swing.JComboBox<String> cbAluno1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JButton jbAcomp;
    private javax.swing.JButton jbCancelar5;
    private javax.swing.JButton jbEnviar5;
    private javax.swing.JButton jbLaudo;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel jlNomeP;
    private javax.swing.JLabel jlNomeP1;
    private javax.swing.JLabel jlNomeP2;
    private javax.swing.JLabel jlNomeU3;
    private javax.swing.JLabel jlNomeU4;
    private javax.swing.JTextArea jtaMenssage5;
    private javax.swing.JTextArea jtaMenssage6;
    private javax.swing.JPanel painel5;
    // End of variables declaration//GEN-END:variables
}
